//
// The rights holder(s) license this file to you under the
// Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You
// may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// For information about copyright ownership, see the NOTICE
// file distributed with this work.
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//

package org.diet4j.core;

import java.util.EventObject;

/**
 * An event generated by a AbstractModuleRegistry. As there is only one kind of event,
 * and ModuleRegistryListener has a specific notification method, there seems
 * to be no point in subclassing this class at this time.
 */
public class ModuleRegistryEvent
        extends
            EventObject
{
    private static final long serialVersionUID = 1L; // helps with serialization

    /**
      * Constructor.
      *
      * @param registry the AbstractModuleRegistry that generated the event
      * @param meta the ModuleMeta to which this event relates
      */
    public ModuleRegistryEvent(
            AbstractModuleRegistry registry,
            ModuleMeta     meta )
    {
        super( registry );

        theModuleMeta = meta;
    }

    /**
     * Obtain the ModuleMeta to which this event relates.
     *
     * @return the ModuleMeta to which this event relates
     */
    public ModuleMeta getModuleMeta()
    {
        return theModuleMeta;
    }

    /**
     * The ModuleMeta to which this event relates.
     */
    protected final ModuleMeta theModuleMeta;
}
